### ISSUE TITLE
Failed to start 1.11.0 with docker compose

### ISSUE THREAD

**Issue by davisskchan** [conduktor/conduktor-platform#134]
Error Log from docker  :

2023-02-07T03:33:34,694Z [testing-agent:ZScheduler-0] ERROR io.conduktor.agent.AgentApp - 
 ❌ Agent failed, reconnecting...
java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:321)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Wrapped by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:7010

[conduktor_logs.txt](https://github.com/conduktor/conduktor-platform/files/10671341/conduktor_logs.txt)

**Comment by guizmaii** [comment]
Hi @davisskchan,

This error shouldn't prevent the Conduktor Platform from booting normally.
The Agent will retry until it succeeds in connecting, as you can see later in the logs:
```bash
2023-02-07 03:33:50,950 DEBG 'testing-agent' stdout output:
2023-02-07T03:33:50,947Z [testing-agent:ZScheduler-0] INFO  io.conduktor.agent.AgentApp - 
 ✅ Agent 'Embedded agent' connected!
```

What is the behaviour that you're experiencing when booting the Docker compose?

**Comment by davisskchan** [comment]
When I open http://localhost:8080, the screen keeps on showing 3 dots waiting.

See 1 error in the docker log : 

2023-02-07T05:17:47,103Z [admin:zio-default-blocking-3] ERROR i.c.a.s.SharedClusterServiceLive - Organization with id 1 is not found

Also attached the whole docker log and docker compose file.

[conduktor_logs.txt](https://github.com/conduktor/conduktor-platform/files/10671735/conduktor_logs.txt)
[docker-compose,txt](https://github.com/conduktor/conduktor-platform/files/10671740/docker-compose.txt)

**Comment by guizmaii** [comment]
Thanks for the additional details @davisskchan 🙏 
I transmitted the issue to the team in charge, we'll come back to you as soon as possible

**Comment by guizmaii** [comment]
Hey @davisskchan,

Thanks for the bug report
It's a bug already known by our teams
A fix for that issue will be put in the next version

Now, to unblock you, you can do these two things:
- Going to http://localhost:8080/admin should mitigate this issue
- if not, clear your browser cookies (If using Chrome, here's how: https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop) and reload the page

Please let us know if that fixed the issue for you 🙂
