### ISSUE TITLE
Error Launch Conduktor with an embedded Kafka (Redpanda)

### ISSUE THREAD

**Issue by doh-ihomis** [conduktor/conduktor-platform#155]
Getting below error when running the default config from docker compose file.

`2023-08-03 12:55:43,318 DEBG 'governance_api' stdout output:
2023-08-03T12:55:43,318Z [governance:ZScheduler-1] INFO  com.zaxxer.hikari.HikariDataSource - metadata-pool - Start completed.

2023-08-03 12:55:43,420 DEBG 'governance_api' stdout output:
timestamp=2023-08-03T12:55:43.404385486Z level=INFO thread=#zio-fiber-24 message="Launch indexer in standalone mode." location=io.conduktor.metadata.indexer.core.sharding.ShardFilter.fromConfig file=ShardFilter.scala line=16

2023-08-03 12:55:44,278 DEBG 'prometheus' stdout output:
ts=2023-08-03T12:55:44.278Z caller=dedupe.go:112 component=remote level=info remote_name=0d1138 url=http://localhost:9009/api/v1/push msg="Done replaying WAL" duration=5.390404951s

2023-08-03 12:55:44,472 DEBG 'governance_api' stdout output:
timestamp=2023-08-03T12:55:44.459639433Z level=ERROR thread=#zio-fiber-278 message="Can't refresh clusters list." cause="Exception in thread "zio-fiber-278" sttp.client3.SttpClientException$ConnectException: Exception when sending request: GET http://localhost:9000/internal/v2/clusters?isPlayground=false
        at sttp.client3.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:13)
        at sttp.client3.SttpClientExceptionExtensions.defaultExceptionToSttpClientException$(SttpClientExceptionExtensions.scala:9)
        at sttp.client3.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:24)
        at sttp.client3.HttpClientAsyncBackend.adjustExceptions$$anonfun$1(HttpClientAsyncBackend.scala:147)
        at sttp.client3.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:35)
        at sttp.client3.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:34)
        at zio.ZIO.tryRescue$1$$anonfun$1(ZIO.scala:359)
        at scala.util.Either.fold(Either.scala:190)
        at zio.ZIO.tryRescue$1(ZIO.scala:359)
        at zio.ZIO.catchSome$$anonfun$1(ZIO.scala:361)
        at sttp.client3.impl.zio.RIOMonadAsyncError.error(RIOMonadAsyncError.scala:24)
        at sttp.client3.impl.zio.RIOMonadAsyncError.flatMap(RIOMonadAsyncError.scala:12)
        at io.conduktor.governance.kafka.HttpClusterConfigurationClient.getClustersToBeIndexed(ClusterConfigurationClient.scala:98)
        at io.conduktor.governance.kafka.HttpClusterConfigurationClient.getClustersToBeIndexed(ClusterConfigurationClient.scala:100)
        at io.conduktor.governance.kafka.HttpClusterConfigurationClient.getClustersToBeIndexed(ClusterConfigurationClient.scala:101)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refreshClustersState(TaskScheduler.scala:91)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refreshClustersState(TaskScheduler.scala:94)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refresh.stream(TaskScheduler.scala:82)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refresh.stream(TaskScheduler.scala:83)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refresh.stream(TaskScheduler.scala:84)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refresh.stream(TaskScheduler.scala:85)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refresh.stream(TaskScheduler.scala:86)
        at io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.make(TaskScheduler.scala:69)
        Suppressed: java.net.ConnectException: null
                at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055)
                at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)
                at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:230)
                at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:206)
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
                at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
                at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
                Suppressed: java.nio.channels.ClosedChannelException: null
                        at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:195)
                        at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:760)
                        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:848)
                        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)
                        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
                        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)
                        at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:230)
                        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:206)
                        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
                        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
                        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
                        at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)" location=io.conduktor.metadata.indexer.core.scheduler.TaskScheduler.refresh.stream file=TaskScheduler.scala line=82`

**Comment by JamesW1** [comment]
Hi @doh-ihomis are you still having this issue? If so, please could you raise it through our official support channel:
https://support.conduktor.io/
