### ISSUE TITLE
testing-agent failed

### ISSUE THREAD

**Issue by remynollet** [conduktor/conduktor-platform#17]
2022-09-08 15:31:42,153 DEBG 'testing-agent' stdout output:
C 2022-09-08T15:31:42.121 Agent failed, reconnect_interval=PT5S, reconnecting... failures={type: io.grpc.StatusRuntimeException; message: UNAVAILABLE: io exception; stacktrace: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.conduktor.agent.AgentApp$.$anonfun$program$10(AgentApp.scala:85)
        at zio.Cause.$anonfun$map$1(Cause.scala:236)
        at zio.Cause.flatMap(Cause.scala:123)
        at zio.Cause.flatMap(Cause.scala:128)
        at zio.Cause.map(Cause.scala:236)
        at zio.ZIO$MapErrorFn.$anonfun$apply$13(ZIO.scala:4552)
        at zio.ZIO$.$anonfun$halt$1(ZIO.scala:3503)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:411)
        at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:785)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:7010
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
        at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:321)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
}

**Comment by rokh-conduktor** [comment]
fixed in 1.0
