### ISSUE TITLE
After upgrading to 1.3.1 io.conduktor.aws.IAMClientCallbackHandler is not longer found

### ISSUE THREAD

**Issue by duartesaraiva98** [conduktor/conduktor-platform#93]
Hello, I bumped conduktor-platform to 1.3.1 this morning and on deployment the following error message popped up:

````
2022-11-07 10:05:36,577 DEBG 'topic_scanner' stdout output:
Both(Empty,Both(Empty,Both(Both(Empty,Both(Fail(org.apache.kafka.common.config.ConfigException: Invalid value io.conduktor.aws.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class io.conduktor.aws.IAMClientCallbackHandler could not be found.,Stack trace for thread "zio-fiber-5,3,1,0":
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:146)
	at org.apache.kafka.clients.admin.AdminClientConfig.<init>(AdminClientConfig.java:231)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:143)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
	at zio.kafka.admin.AdminClient.javaClientFromSettings(AdminClient.scala:1134)
	at zio.kafka.admin.AdminClient.fromManagedJavaClient(AdminClient.scala:1129)
	at io.conduktor.topicscanner.api.BrokerDiscoveryLive.createClientAdmins(BrokerDiscovery.scala:52)
	at io.conduktor.topicscanner.api.BrokerDiscoveryLive.createClientAdmins(BrokerDiscovery.scala:43)
	at io.conduktor.topicscanner.api.BrokerDiscoveryLive.createClientAdmins(BrokerDiscovery.scala:54)
	at io.conduktor.topicscanner.api.BrokerDiscoveryLive.layer(BrokerDiscovery.scala:117)
	at io.conduktor.topicscanner.api.BrokerDiscoveryLive.layer(BrokerDiscovery.scala:113)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220)),Then(Then(Interrupt(Runtime(3,1667815535019,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-3,6,1,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220)),Interrupt(Runtime(3,1667815535019,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-3,6,1,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220))),Interrupt(Runtime(3,1667815535019,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-3,1,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220))))),Then(Then(Then(Interrupt(Runtime(1,1667815534994,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-1,4,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220)),Interrupt(Runtime(1,1667815534994,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-1,4,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220))),Interrupt(Runtime(1,1667815534994,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-1,4,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220))),Interrupt(Runtime(1,1667815534994,io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)),Stack trace for thread "zio-fiber-1,0":
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.program(TopicScannerCli.scala:210)
	at io.conduktor.topicscanner.cli.TopicScannerCli.run.x$21(TopicScannerCli.scala:220))))))
````

**Comment by guizmaii** [comment]
Hey @duartesaraiva98,

The `topic_scanner` software is not yet compatible with IAM but the rest of the Platform (Console and Testing) are compatible

The support of IAM for all the Platform is coming soon

I'm closing the ticket. Don't hesitate to reopen it if you feel the need

Thanks for the feedback
🙂

**Comment by duartesaraiva98** [comment]
@guizmaii Thanks for the quick response :smile: 

This actually a great bridge to another question I have. Currently our configuration for enabled modules looks like this:
````
CONSOLE_ENABLED: true
DATA_MASKING_ENABLED: true
TESTING_ENABLED: false
MONITORING_ENABLED: false
SCANNER_ENABLED: false
GOVERNANCE_ENABLED: false
````

I notice in the logs that most processes are still spawned:

````
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Testing" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Testing embedded agent" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Governance" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Data-masking" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Topic analytic" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Monitoring - Alert manager" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Monitoring - Cortex" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Monitoring - Lag exporter" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Monitoring - API" disabled by env
[2022-11-07T10:04:21Z INFO  platform_cli::module_flags::domain] Module "Monitoring - Prometheus" disabled by env
....
2022-11-07 10:04:22,842 INFO spawned: 'postgresql' with pid 35
2022-11-07 10:04:22,844 INFO spawned: 'authenticator' with pid 36
2022-11-07 10:04:22,846 INFO spawned: 'crond' with pid 37
2022-11-07 10:04:22,848 INFO spawned: 'kafka_monitoring_api' with pid 38
2022-11-07 10:04:22,850 INFO spawned: 'admin-portal' with pid 39
2022-11-07 10:04:22,853 INFO spawned: 'console' with pid 40
2022-11-07 10:04:22,855 INFO spawned: 'testing' with pid 41
2022-11-07 10:04:22,857 INFO spawned: 'testing-agent' with pid 42
2022-11-07 10:04:22,858 INFO spawned: 'platform_api' with pid 43
2022-11-07 10:04:22,860 INFO spawned: 'prometheus' with pid 44
2022-11-07 10:04:22,863 INFO spawned: 'alertmanager' with pid 45
2022-11-07 10:04:22,872 INFO spawned: 'cortex' with pid 46
2022-11-07 10:04:22,885 INFO spawned: 'data_masking' with pid 47
2022-11-07 10:04:22,892 INFO spawned: 'governance_api' with pid 48
2022-11-07 10:04:22,896 INFO spawned: 'topic_scanner' with pid 49
2022-11-07 10:04:22,904 INFO spawned: 'kafka_lag_exporter' with pid 53
2022-11-07 10:04:22,984 INFO spawned: 'proxy' with pid 58
````

When configuring `conduktor-platform` I would expect that `SCANNER_ENABLED=false` would disable the `topic_scanner`. 

I am making a wrong assumption here or is something going wrong?

**Comment by guizmaii** [comment]
> I am making a wrong assumption here or is something going wrong?

I'm not competent to answer this question. I'

**Comment by rokh-conduktor** [comment]
Hello @duartesaraiva98,
Thanks for reporting this issue!
We will provide a fix in an upcoming version.
